slice_name: Average and Sum Trends
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: AVG
    column:
      column_name: num
      type: BIGINT(20)
    expressionType: SIMPLE
    label: AVG(num)
    optionName: metric_vgops097wej_g8uff99zhk7
  metrics_b:
  - sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: mixed_timeseries
  yAxisIndex: 0
  yAxisIndexB: 1
query_context: null
cache_timeout: null
uuid: 0fc62369-2a53-420e-8831-228decf4f25e
version: 1.0.0
dataset_uuid: 8c4f5d98-8f3e-4206-b6b6-7add4224e1e8
