slice_name: Monthly Sales
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 28__table
  viz_type: echarts_timeseries_line
  x_axis: country
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: quantity_ordered
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 776
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: 74905e1a-20e9-48fd-9460-37357774063a
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(quantity_ordered)
    optionName: metric_sjzpgb2xs4n_y1g1umpqwyr
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: order_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastEnabled: false
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  sort_series_ascending: false
  color_scheme: supersetColors
  time_shift_color: true
  show_value: false
  only_total: true
  percentage_threshold: 0
  area: false
  opacity: 0.2
  markerEnabled: false
  markerSize: 6
  zoomable: false
  minorTicks: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: false
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":28,"type":"table"},"force":false,"queries":[{"filters":[{"col":"order_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"country","label":"country","expressionType":"SQL","isColumnReference":true}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"quantity_ordered","description":null,"expression":null,"filterable":true,"groupby":true,"id":776,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"74905e1a-20e9-48fd-9460-37357774063a","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(quantity_ordered)","optionName":"metric_sjzpgb2xs4n_y1g1umpqwyr"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"quantity_ordered","description":null,"expression":null,"filterable":true,"groupby":true,"id":776,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"74905e1a-20e9-48fd-9460-37357774063a","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(quantity_ordered)","optionName":"metric_sjzpgb2xs4n_y1g1umpqwyr"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["country"],"columns":[],"aggregates":{"SUM(quantity_ordered)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"28__table","viz_type":"echarts_timeseries_line","x_axis":"country","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"quantity_ordered","description":null,"expression":null,"filterable":true,"groupby":true,"id":776,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"74905e1a-20e9-48fd-9460-37357774063a","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(quantity_ordered)","optionName":"metric_sjzpgb2xs4n_y1g1umpqwyr"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"order_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastEnabled":false,"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title":"","x_axis_title_margin":15,"y_axis_title":"","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","sort_series_ascending":false,"color_scheme":"supersetColors","time_shift_color":true,"show_value":false,"only_total":true,"percentage_threshold":0,"area":false,"opacity":0.2,"markerEnabled":false,"markerSize":6,"zoomable":false,"minorTicks":false,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelRotation":0,"xAxisLabelInterval":"auto","rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":false,"tooltipSortByMetric":false,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateXAxis":true,"truncateYAxis":false,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 1d68e974-7a85-4d0b-819e-8ce6f69ca82e
version: 1.0.0
dataset_uuid: 7d02f5ad-1034-4d54-aa6a-e1c359b8db71
