slice_name: Top Vaccine Category by Country
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  viz_type: echarts_timeseries_bar
  x_axis: country_name
  x_axis_sort: country_name
  x_axis_sort_asc: false
  x_axis_sort_series: sum
  x_axis_sort_series_ascending: false
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(candidate_count)
    label: Candidates
  groupby:
  - product_category
  adhoc_filters: []
  row_limit: 10000
  series_limit: 10
  order_desc: true
  show_legend: true
  rich_tooltip: true
  color_scheme: supersetColors
  orientation: vertical
  show_value: false
  stack: true
  only_total: true
  truncateYAxis: false
  datasource: 29__table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 967b62a7-f108-4a86-b196-52b16b1a6449
version: 1.0.0
dataset_uuid: 528402c6-b186-4e09-bb52-7c2665e2bca4
