slice_name: Trends
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  rich_tooltip: true
  row_limit: 50000
  show_legend: true
  time_range: '100 years ago : now'
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: 778921a1-dcf3-4023-a464-c1244cb188e8
version: 1.0.0
dataset_uuid: 8c4f5d98-8f3e-4206-b6b6-7add4224e1e8
